// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ConfigProvider: typeof import('./modules/config-provider/index.vue')['default'];
    RefDemo: typeof import('./modules/base/ref-demo/index.vue')['default'];
    RefSetupDemo: typeof import('./modules/base/ref-setup-demo/index.vue')['default'];
  }
}

export {};
