// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppPropsDemo: typeof import('./app-props-demo/index.vue')['default']
    ConfigProvider: typeof import('./config-provider/index.vue')['default']
    HttpDemo: typeof import('./http-demo/index.vue')['default']
    RefSetupDemo: typeof import('./ref-setup-demo/index.vue')['default']
    Theme: typeof import('./theme/index.vue')['default']
  }
}
